### ISSUE TITLE
Category widget UI

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#781] opened 2015-11-06 17:43 UTC
Some issues with category widget:

 1. Is that correct? Or should be fully empty, no green at all?
 2. Categories should be normalised based on the category with more results. In this case USA should use 100% of the width and CAN and MEX adjusted accordingly so they are easier to compare.

![screen shot 2015-11-06 at 18 29 17](https://cloud.githubusercontent.com/assets/45346/11003897/8d8b8586-84b5-11e5-9b8d-e799c073e3c0.png)

cc @saleiva

**Comment by xavijam** [comment] 2015-11-06 17:48
1. That min value is ok, requested by design team.
2. Oh, really? I though it was based on the total number of occurences...

**Comment by xavijam** [comment] 2015-11-10 09:51
Fixed in widgets branch.

**Closed by xavijam** 2015-11-10 09:51 UTC
Labels: widgets
