### ISSUE TITLE
Vector tiles issues

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb.js#1668] opened 2017-06-06 09:59 UTC
After testing some of [my public embed maps](https://team.carto.com/u/ramirocartodb/maps), these are the issues that have come up:

### Embed maps urls

* Bubble map: https://ramirocartodb.carto.com/builder/dd95752c-446d-11e7-9d8d-0e233c30368f/embed
* Points + Polygons (`polygon-gamma: 0.5`): https://ramirocartodb.carto.com/builder/d052ad86-2347-11e7-802c-0ee66e2c9693/embed
* Points + Lines (`line-color: [color];`): https://ramirocartodb.carto.com/builder/a26f9b27-8176-4f41-bdda-6415193a911c/embed
* Polygons (low zoom levels, `polygon-gamma: 0.5`) + Points (high zoom levels): https://ramirocartodb.carto.com/builder/7b743d5c-1b90-11e7-9455-0e05a8b3e3d7/embed
* Torque (static): https://ramirocartodb.carto.com/builder/8846ac54-154b-11e7-b277-0e3ff518bd15/embed

### Issues

* The initial loading takes more time than with rasters.
* Smooth zoom transitions are not constant. Sometimes the transition is quite harsh. 
* 3-4 times, the browser collapses. Blank pages appear in all tabs where embed maps are loading.

cc @jorgesancha

**Comment by donflopez** [comment] 2017-06-06 14:14
Good points @ramiroaznar!! Thank you :)

All the maps that render in raster are because of unsupported features in the CCSS.

About the timing... It could be requesting time or rendering time, could be great if you provide information about the request timing for the .mvt tiles.

The browser collapses because of is quite different to have multiple embeds with images than with mvt stored in the ram (with all the data). For the same domain (this could change with new versions of chrome), the browser uses *process-per-site-instance*, so you are running multiple vector maps with the same thread and if one of them causes a process failure, all of them will crash.

> By default, Chromium creates a renderer process for each instance of a site the user visits.
>Concretely, we define a "site" as a registered domain name (e.g., google.com or bbc.co.uk) plus a scheme (e.g., https://). This is similar to the origin defined by the Same Origin Policy, but it groups subdomains (e.g., mail.google.com and docs.google.com) and ports (e.g., http://foo.com:8080) into the same site. 

[+ info](https://www.chromium.org/developers/design-documents/process-models)

We have to study tangram performance (possible leaks, data duplication, etc...), think about data simplification in server side and have in mind that the feature limit is not realistic, you can have a feature with a polygon with 1M of vertexes.

For the rest, we have to improve the support (or remove/ignore those properties). You can see currently supported features [here](https://github.com/CartoDB/tangram-reference/blob/master/1.0.0/reference.json)

Thank you again @ramiroaznar!

**Comment by ramiroaznar** [comment] 2017-06-06 14:35
Love to have those insights, Paco! 

Btw I will be off this afternoon and tomorrow. @jorgesancha if you want us to test this further, please ping Solutions via email or open an issue in solutions repo. The rest of the team will be happy to help. :-)

**Comment by ramiroaznar** [comment] 2017-06-06 21:57
I have found that auto-style is not working on [this map](https://team.carto.com/u/ramirocartodb/builder/975306b2-05fa-4075-b468-174afe614d04/embed) (maybe related to `com-op` properties).

**Comment by donflopez** [comment] 2017-06-06 21:59
You just have to open the dev tools and look at the console.

```
Error: :11:2 Invalid value for marker-comp-op, the type keyword (options: multiply, add, overlay) is expected. screen (of type keyword)  was given.
```

This is the error for that map, as you said, the `comp-op`.

Thanks @ramiroaznar! ☺️

**Comment by javisantana** [comment] 2017-06-08 16:59
some others: 

https://team.carto.com/u/javi/builder/d183f93d-032d-4e66-9357-069bf76b8a9f/embed <- does not render anything
https://team.carto.com/u/javi/builder/df61daec-d977-11e5-a52d-0e787de82d45/embed <- does not render line strokes

**Comment by donflopez** [comment] 2017-06-12 10:08
The first map has a problem with layers names, in the layer collection we have an id for the layer and in the mvt tile we have another. That is why we can't draw a thing.

In the second the problem is the marker-fill-opacity property, if we have 0, we don't render... I'll fix that ASAP.

Thank you for the feedback @javisantana! 🎉

**Comment by stevelewis99** [comment] 2017-06-14 15:27
Here's one I just tested and found some issues with lines (from connect with lines analysis):
https://team.carto.com/u/steve-carto/builder/3a6f92f7-fa75-4a1a-8df1-b917d73933e6/embed

Console has lots of these errors:
tracker.js:15 Tangram v0.12.1 [error]: Style.parseFeature: style parsing error 
Object {type: "Feature", geometry: Object, properties: Object}

If I make the lines layer invisible and republish, the errors go away and also the other layer (area of influence) now appears (previously they did not appear)

Can supply a .carto if you need it!

**Comment by donflopez** [comment] 2017-06-14 16:16
Hi @stevelewis99!

Thank you for your feedback, the fix is waiting for being merged [here](https://github.com/CartoDB/cartodb/pull/12327)!

**Comment by alonsogarciapablo** [comment] 2017-09-04 15:23
@jorgesancha closing this issue for now. Please reopen it if you think it's important.

**Closed by alonsogarciapablo** 2017-09-04 15:23 UTC
Labels: vector
