### ISSUE TITLE
Zooming on histograms won't take new data from GeoJSONDataProvider

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb.js#1058] opened 2016-02-08 18:21 UTC
When zooming in on a histogram, it should generate a new one through the data provider, using new data from the layer. However, right now it's bypassing the histogram function and generating a chart with old data.

![hist](https://cloud.githubusercontent.com/assets/3707222/12894775/1bbbceb0-ce99-11e5-9fc5-7b6404d6f616.gif)

@javisantana @alonsogarciapablo

**Comment by javisantana** [comment] 2016-02-08 20:30
@alonsogarciapablo I think it's related to the way we get the data from datasource for the small histogram. I have some concerns about that

**Comment by acanimal** [comment] 2016-02-09 08:49
@alonsogarciapablo I also have some issues with histogram on cartod1b because of its casuistic. Let me know when you work on this issue so we can talk together about how to address.

**Comment by alonsogarciapablo** [comment] 2016-02-10 17:31
This is a duplicate of #1069.

**Closed by alonsogarciapablo** 2016-02-10 17:31 UTC
