### ISSUE TITLE
google maps createvis not working as expected

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#309] opened 2015-02-03 08:35 UTC
see attached

![screen_shot_2015-02-02_at_17 10](https://cloud.githubusercontent.com/assets/36676/6016838/e3e8764e-ab87-11e4-88c8-7b4adf6c2585.png)

also, torque layer didn't appear in embed

**Comment by javisantana** [comment] 2015-02-03 08:39
@matallo attach the viz.json please

**Comment by Xatpy** [comment] 2015-02-03 09:08
@matallo is it from [this](http://srogers.cartodb.com/viz/81916204-c392-11e3-bcbf-0e230854a1cb/embed_map?title=true&description=true&search=true&shareable=true&cartodb_logo=true&layer_selector=false&legends=true&scrollwheel=true&fullscreen=true&sublayer_options=1%7C1&sql&sw_lat=11.821410465077479&sw_lon=60.335443281250036&ne_lat=27.525102650180578&ne_lon=99.93016984375004) visualization?

**Comment by matallo** [comment] 2015-02-03 09:22
indeed, the embed it's failing in chrome, too

![screen shot 2015-02-03 at 10 20 38](https://cloud.githubusercontent.com/assets/36676/6017498/86db1c0c-ab8e-11e4-85ad-436edda94f5d.png)

**Comment by Xatpy** [comment] 2015-02-03 09:25
Yes, but it's failing with the Torque bug that I think that was resolved by @fdansv yesterday. Could it be?
![screen shot 2015-02-03 at 10 22 07](https://cloud.githubusercontent.com/assets/3958416/6017514/c902d11a-ab8e-11e4-997b-67c33e2cbbe8.png)

Also, @matallo , I checked that cartodb.js used in the web-page is: `http://libs.cartocdn.com.s3.amazonaws.com/cartodb.js/v3/3.11/cartodb.js`
instead of being from fastly. Could it be anything related?

**Comment by fdansv** [comment] 2015-02-03 09:28
Yes this has been just merged to cartodb.js

**Comment by matallo** [comment] 2015-02-03 09:32
@Xatpy uhm, if it's being resolved in a newer cdb.js version just file an issue in the website repo to update the script, thanks!

**Comment by Xatpy** [comment] 2015-02-03 11:24
The map is working if it's alone, but it isn't working from the website. 
I think that the problem is that this map is cached at Varnish.
I'll create a pull request in web-site repo trying to fix it.

**Comment by Xatpy** [comment] 2015-02-03 14:16
It's a problem with the [viz.json](http://srogers.cartodb.com/api/v2/viz/006e0472-da74-11e3-acea-0e10bcd91c2b/viz.json)

It has: `map_provider: "googlemaps",` and then it also has `options: {
visible: true,
type: "Tiled",
name: "Dark matter",`in its layer options.

**Comment by Xatpy** [comment] 2015-02-03 14:52
Solved. 
I had to convert provider to leaflet in his account. Viz.json is now updating and working. Tested with Chrome, Safari and Firefox.
![screen shot 2015-02-03 at 15 49 17](https://cloud.githubusercontent.com/assets/3958416/6022367/84c080c8-abbc-11e4-9184-87933be55e17.png)
thanks guys!

**Closed by Xatpy** 2015-02-03 14:52 UTC
