### ISSUE TITLE
Application broken with new cartodb.js v3.12.13

### ISSUE THREAD

**Issue by russmo** [CartoDB/cartodb.js#408] opened 2015-03-18 17:27 UTC
I get this error in my console with the new cartodb.js v3.12.13 released 8 hours ago.

Uncaught ReferenceError: Mustache is not defined    cartodb.js:14

My application fails to load.  Switching to previous 3.12.12 or any earlier release fixes the issue.

**Comment by alonsogarciapablo** [comment] 2015-03-18 17:42
Hello @russmo. I'm happy to investigate what's going on here. I will need some more info. What are you doing exactly?

**Comment by russmo** [comment] 2015-03-18 18:50
I dropped CartoDB into an existing application a few days ago.  It’s loaded by require.js along with other libraries, so it’s not quite a plain vanilla setup.  Require is also pulling in jquery, underscore, backbone, and my custom app.js.  I know cartodb.js has some of those bundled inside of it, so I can see how there might be some conflicts.

What is strange is that everything worked fine a few days ago, it just failed out with today’s 3.12.13 release.  Anything earlier works as expected.  I’m wondering what might have changed between 3.12.12 and 3.12.13 to change this behavior?

**Comment by alonsogarciapablo** [comment] 2015-03-18 19:29
@russmo. The main change in v3.2.13 is the upgrade of mustache.js from v0.5.2 to v1.1.0, which is totally related to the error you're seeing. Are you including your own version of mustache.js?

**Comment by russmo** [comment] 2015-03-18 21:00
I am not using mustache.js.  I just updated my backbone and underscore to the latest stable versions in my app and I still get the error.  I’m sure there’s something weird going on with require.js asynchronous script loading and something getting loaded before it should.

cartodb.js:14 Uncaught ReferenceError: Mustache is not defined
require.js:27 Uncaught Error: Mismatched anonymous define() module: [object Object]
http://requirejs.org/docs/errors.html#mismatch

**Comment by russmo** [comment] 2015-03-18 21:57
I just tested loading only cartodb.js as the only script via require.js and it has the same Mustache-related error.  I wonder if there is something in Mustache v1.1 that detects if it is loaded via an AMD loader (e.g., require.js) and doesn’t export a global Mustache object.

**Comment by javisantana** [comment] 2015-03-19 07:41
Could you provide a small html to reproduce the problem ?

**Comment by alonsogarciapablo** [comment] 2015-03-19 10:11
This is not a cartodb.js issue. It seems that Mustache.js and require.js do not work well together.

Here's [an example that reproduces the problem](http://codepen.io/alonsogarciapablo/pen/NPeGOr).

@russmo are you loading cartodb with a `script` tag? It would be great if you could share your code with us.

**Comment by russmo** [comment] 2015-03-19 19:19
You're right.  It's not an issue in the cartodb module.  It's just an artifact that pops up if a user's app uses require.js or another AMD script loader based on the way cartodb.js aggregates its dependencies.  If Mustache detects a 'define' function, it loads as an AMD module and doesn't export a global Mustache object.  The older Mustache version in 3.12.12 and earlier didn't do this.  The cartodb module looks for a global Mustache and doesn't find one.

The only way to prevent this in a page with require.js is to either put cartodb.js in a script tag above require.js or make sure a Mustache.js is loaded in a script tag before require.js.  Like this:
http://codepen.io/anon/pen/raoWBE
This makes everything happy by including a version of Mustache in a script tag above the require script tag.  I can define cartodb as a dependency for my app and it loads jquery, leaflet, and cartodb happily.  It finds a window.Mustache global, so it doesn't complain upon loading.  I make sure cartodb's bundled Mustache is put back in the global.  It's just an ugly hack.  The advantage is that I can have a number of pages/apps just require 'mycartodb' and they'll get the right libraries loaded in the right order.  I have a number of leaflet plugins to load and requirejs makes sure they are loaded in the right order.

The alternative is that I just load cartodb in a script tag ABOVE the require.js tag anywhere I need cartodb.  This works fine.  I just need to make sure this is done above require.js anytime I need leaflet and some cartodb layers.

**Comment by alonsogarciapablo** [comment] 2015-03-20 09:15
Thanks for the example @russmo! We are closing this issue since it's not a cartodb.js. If more people report this issue, we will think about a way to make cartodb/mustache work with require.js. Thanks!

**Closed by alonsogarciapablo** 2015-03-20 09:15 UTC
