### ISSUE TITLE
dataviews return forbidden error when using auth api beta with carto.js v4 beta

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb.js#2071] opened 2018-03-19 09:02 UTC
When creating an API key with `maps` permission for a private dataset and using this api key for a CARTO.js v4 beta, the map is rendered correctly.

However, when adding a Formula dataview, CARTO.js v4 is returning me the next error message:

![screen shot 2018-03-19 at 09 54 49](https://user-images.githubusercontent.com/11177693/37586120-a7775da4-2b5b-11e8-81f6-c1d7d773fe55.png)

![screen shot 2018-03-19 at 09 55 14](https://user-images.githubusercontent.com/11177693/37586131-aa3d46ca-2b5b-11e8-8add-bc7e99d8e28f.png)

If I try to add SQL permissions to the dataset, I get the same error.

I'm attaching the code of the map here:

[auth_api_cartojsv4.html.zip](https://github.com/CartoDB/cartodb.js/files/1824298/auth_api_cartojsv4.html.zip)

**Comment by ivanmalagon** [comment] 2018-03-21 11:58
Tested against my account. It happens the same.

The error is returned by the dataview URL

Request to
```
http://0.ashbu.cartocdn.com/hacheka/api/v1/map/a58e0f800a28170c476dd1bed127469a:0/dataview/formula-c4?
```

Response
```
{
  "errors": [
    "permission denied for relation airbnb_listings"
  ],
  "errors_with_context": [
    {
      "type": "unknown",
      "message": "permission denied for relation airbnb_listings"
    }
  ]
}
```

**Comment by dgaubert** [comment] 2018-03-21 12:04
I'm missing something, where is the `api_key` in that request?

**Comment by ivanmalagon** [comment] 2018-03-21 12:09
It's normal that you don't see the api_key... because it's not there.

![que yo la vea](https://user-images.githubusercontent.com/1078228/37708990-075e4fee-2d09-11e8-8343-010e86e0b1c4.gif)

**Comment by ivanmalagon** [comment] 2018-03-23 09:55
CARTO.js already published to npm and our CDN.

`v4.0.0-beta.37`

#### CDN

[https://cartodb-libs.global.ssl.fastly.net/carto.js/v4.0.0-beta/carto.min.js](https://cartodb-libs.global.ssl.fastly.net/carto.js/v4.0.0-beta/carto.min.js)

#### NPM

[https://www.npmjs.com/package/carto.js](https://www.npmjs.com/package/carto.js)

**Comment by jsanz** [comment] 2018-03-23 11:14
Confirmed, Maps only API key working with dataviews here https://codepen.io/jsanz/pen/wmeMLo

Awesome @ivanmalagon

**Comment by ramiroaznar** [comment] 2018-03-23 14:51
@ivanmalagon should we close this?

**Comment by ivanmalagon** [comment] 2018-03-23 15:26
Shipped (in Builder) 🚀

**Closed by ivanmalagon** 2018-03-23 15:26 UTC
