### ISSUE TITLE
[Google Map Support] Review Torque Layers

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1528] opened 2016-12-09 16:01 UTC
There’s a JS error that is preventing animated layers from being rendered correctly.

**Comment by alonsogarciapablo** [comment] 2017-01-12 13:11
Assigned this to @donflopez as discussed with @javisantana and @rochoa.

**Comment by donflopez** [comment] 2017-01-12 16:57
Hey, I saw the problem. The main problem seems to be a bad conf instantiation, the error happens [here](https://github.com/CartoDB/torque/blob/master/lib/torque/gmaps/torque.js#L118). 

The problem is that `this.options.map` is undefined and the correct map reference is at 'this.map'.

I'll check where is the mistake next week!

**Comment by donflopez** [comment] 2017-01-17 10:59
#Acceptance Criteria:#

*Prerequisites:*
- Clone v4-gmaps-torque branch
- npm i
- Clone [torque branch](https://github.com/CartoDB/torque/tree/gmaps-support)
- go to torque folder
- make
- npm i && npm link
- go to cartodb.js
- npm link torque.js
- grunt dev

*Try gmaps torque demo:*
- Go to examples -> v4 -> gmaps-torque example
- Everything should work
- Go to all others examples, everything should work

**Comment by jgoizueta** [comment] 2017-02-07 13:44
Acceptance testing:

I've noticed a couple of funny things with the gmaps-torque example.

At the levels where the maps repeats cyclically on the horizontal (longitude) axis, the torque layer seems to be drawn in the instance closest to the page center and jump when the map is panned, unlike what happens for leaflet maps, where the torque layer repeats for each repetition of the base map.

Sometimes the placement seems a little surprising as in the expample at zoom level 2 where the chosen map instance, the one on the right seems less centered than the left one:

![screen shot 2017-02-07 at 13 57 40](https://cloud.githubusercontent.com/assets/5909/22692970/9dc762bc-ed41-11e6-9967-8ccfb0580d99.png)

But the real problem I've found is that for zoom level 3 the torque layer didn't appear at all. 

No js errors appear in the console (nor network errors); only these warnings:

![screen shot 2017-02-07 at 13 53 18](https://cloud.githubusercontent.com/assets/5909/22693013/d15f9cf2-ed41-11e6-93b4-1eebccf5b71c.png)

**Comment by jgoizueta** [comment] 2017-02-07 13:55
Just a little clarification: this image shows how the torque layer is visible only on one of the multiple map repetitions, and it's also the (level 1) zoom before zooming in to the image (level 2) in the previous comment (so the torque layer seems to jump to the right)

![screen shot 2017-02-07 at 13 58 03](https://cloud.githubusercontent.com/assets/5909/22693884/63566872-ed45-11e6-9252-a4ee62e3dc20.png)

**Comment by donflopez** [comment] 2017-02-07 16:05
Thank you @jgoizueta!! I'll take a look :)

**Comment by javisantana** [comment] 2017-02-07 16:07
that's a known issue, I'd not spend time on that if we have other issues

**Comment by donflopez** [comment] 2017-02-07 16:09
Perfect, should I merge the PR?

cc/ @alonsogarciapablo

**Comment by alonsogarciapablo** [comment] 2017-02-08 09:43
🚀

**Comment by alonsogarciapablo** [comment] 2017-02-16 15:22
@donflopez can we close this issue? Has this been deployed? Thanks!

**Comment by donflopez** [comment] 2017-02-17 09:04
Yes! Is it merged into carto master branch

**Closed** 2017-02-17 09:04 UTC
