### ISSUE TITLE
Adapt sources as references

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1785] opened 2017-09-28 10:05 UTC
Integrates #1771, #1755

Related PRs:
- CARTO.js: https://github.com/CartoDB/cartodb.js/pull/1804
- deep-insights: https://github.com/CartoDB/deep-insights.js/pull/596
- CartoDB: https://github.com/CartoDB/cartodb/pull/12850

**Comment by ivanmalagon** [comment] 2017-09-29 13:47
Found an issue passing acceptance.

### Steps to reproduce

1. Create a map with a layer with data. The layer will be `a`.
2. Add a widget from a column of that layer. The widget will point to `a0`.
3. Create an analysis on top of `a0`. A simple one like `subsample` will make the trick.
4. Drag and drop `a0` to create another layer. It'll be `b`.
5. At this point, the widget will point to the dragged node, now pointing to `b0`.
6. Delete layer `b`.

### Current result

The widget still points to `b0` (that doesn't exist anymore) but if you inspect the map instantiation payload, the dataview is assigned to `a0` (which is correct.)
When you refresh the map, since the widget model is pointing to a non-existing node, it doesn't render.

### Expected result

The widget is reassigned to `a0` and when the user refresh, the widget is still there.

### Reason

The most likely reason is that the widget model is not notified of this change. The dataview is correctly notified but not the widget.

The dataview and the widget should be synchronised.

**Comment by alonsogarciapablo** [comment] 2017-09-29 13:53
My opinion... if this is something that was already happening in production, I'd solve it as a separate issue. It doesn't look like is something we broke as a result of working with source objects in CARTO.js...

**Comment by alonsogarciapablo** [comment] 2017-10-03 16:32
I deployed this to `ded13` but I'm not sure it's really there... If we used tags for cartodb.js and deep-insights.js and log the version in the console ([we're doing that in cartodb.js already](https://github.com/CartoDB/cartodb.js/commit/1ec2cd33e8b21925fa6a64ad9767b43a9a43acc9)), we could make sure the code that we're testing has been deployed (cc: @Jesus89 @IagoLast @ivanmalagon)

**Comment by IagoLast** [comment] 2017-10-04 06:09
@alonsogarciapablo maybe adding a version number to the global object.


`carto.version ---> 4.0.0-alpha.3`

**Comment by ivanmalagon** [comment] 2017-10-04 07:35
It was deployed. A 'cuenta de la vieja' mode of checking it is to open DevTools and search a file with a change done in that PR.

But, for sure, it's better to reflect that on the `cartodb.js` version number.

**Comment by Jesus89** [comment] 2017-10-04 12:47
In production! :rocket:

**Closed by Jesus89** 2017-10-04 12:47 UTC
Labels: hacktoberfest, integration, sources-as-references
