### ISSUE TITLE
No official release for v4

### ISSUE THREAD

**Issue by A----** [CartoDB/cartodb.js#1601] opened 2017-03-21 13:08 UTC
Is there an official release of the v4 out or planned, as it seems possible to do have v4 features in maps now?
Will it be available through bower?

Those maps cannot seem to use `v2` API and the CartoDB.js 3.x.

---

> Below is an issue that I was having integrating v4 maps using CartoDB.js.  
> I'll keep it here for future reference.
>
> The solution was to change the api version you query when using createViz, from  
> `https://{account}.cartodb.com/api/v2/viz/{viz-id}/viz.json`
> to
> `https://{account}.cartodb.com/api/v3/viz/{viz-id}/viz.json` (notice the `v3` here)  
> Lucky guess.

I have a client with a premium account on Carto, and I'm doing some custom integration of his maps on his website.  
The issue is that he uses some v4 features, making tooltips displayed all wrong (no CSS). Also, there's no +/- zoom controls.

## Expected results

All features work correctly when integrating a map using cartodb.js.

## Actual , embed view

Embed view works fine, tooltip is displayed. In the console, `cartodb.js 4.0.0-alpha.1` is displayed.

## Actual, using CartoDB.js 3.15.9

Map is displayed, but tooltips do not have CSS styling. In the console, `cartodb.js 3.15.8` is displayed.  
Checking the `.bower.json` and all, the 3.15.9 is correctly installed.

I do have an error in the `error` "method" of the `createViz` : `zoom template is empty`.  
I do not have zoom controls.

## Attempt 1, upgrading to latest bower release

Latest tagged version is 3.15.10 on the `CartoDB/cartodb.js-bower` repository.  
Same results.

## Attempt 2, building v4 HEAD branch

There are no official 4.x release or tag, so building the v4 branch it is.  
I do have the following in my console : `cartodb.js 4.0.0-alpha.1`

But I have the following stack:

```
Uncaught TypeError: Cannot read property 'maps_api_template' of undefined
    at L.d.load (vis.js:105)
    at k (create-vis.js:95)
    at Object.current (create-vis.js:36)
    at window.vizjson (loader.js:63)
    at viz.json?callback=vizjson:1
```

**Comment by jsanz** [comment] 2017-03-21 15:05
There is no release of `v4` at this moment and if the user is creating maps with BUILDER then then there is no `viz.json` endpoint compatible with cartodb.js 3.

If the user is on a paid account on carto.com then he should write to `support@carto.com` or `enterprise-support@carto.com` (depending on his plan) so we can handle from there. Otherwise, since there is no `viz.json` support for BUILDER you need to use anonymous maps or named maps.

Closing this issue since this is expected behavior.

**Closed by jsanz** 2017-03-21 15:05 UTC
